---
title: "Arboles ventas"
author: "Maria Belen Franco Ovando"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Árboles de Decisión

```{r}
library(car)
library(readxl)
DATA_FINAL <- read_excel("~/Diplomado/Modulo VI/Trabajo Final/Data Final/DATA FINAL.xlsx")
Categoria <- factor(Categoria, levels = c("Accesorios","Bicicletas","Ropa"), labels = c("Accesorios", "Bicicletas", "Ropa"))
Costo <- DATA_FINAL$Costo
Precio <- DATA_FINAL$Precio
Tabla = data.frame(Costo, Precio, Categoria)
Tabla
summary(Tabla)
```

## Matriz de Covarianza

```{r}
library(scatterPlotMatrix)
scatterPlotMatrix(Tabla)
```


Existe una correlación entre costo y precio. 

## Entrenamiento de árbol de decisión

```{r}
library(party)
attach(Tabla)
str(Tabla)    
# describe al objeto transit y muestras las columna que tiene
ind <- sample(2, nrow(Tabla), replace=TRUE, prob=c(0.7, 0.3))  
ind  
```


```{r}
trainData <- Tabla [ind==1,]
# genero un set de entrenamiento 
testData <- Tabla [ind==2,]    
# genero un set de datos de prueba
myFormula <- Categoria ~ Costo + Precio
transit_ctree <- ctree(myFormula, data=trainData)    
# creo el motor de entrenamiento
# Verificar las prediciones 
table(predict(transit_ctree), trainData$Categoria) 
print(transit_ctree) 
```

# Impresión del Árbol de Decisión

```{r}
plot(transit_ctree, las=2)
```

```{r}
summary(trainData$Categoria)
```